steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/kr-live-epg:$COMMIT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/kr-live-epg:$COMMIT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - kr-live-epg
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/kr-live-epg:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --no-allow-unauthenticated
      - --cpu=1
      - --memory=512Mi
      - --min-instances=0
      - --max-instances=1
      - --concurrency=1
      - --timeout=300
substitutions:
  _REGION: europe-central2
  _REPOSITORY: kr-live-epg
options:
  logging: CLOUD_LOGGING_ONLY
